### ISSUE TITLE
EPIC: Posts

### ISSUE THREAD

**Issue by Euromantic** [ginside-pub/ginside-backend#1]
- [x] Model
- [x] API
- [x] Filter by archive state
- [ ] Authors
- [ ] Auto-assign author
- [ ] Posts by authors
- [ ] Length limits
- [ ] Tags
- [ ] Textual IDs
- [ ] Markdown render
